In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../datasets/final_dataset_missing_value_imputed_v5.csv')

In [4]:
df.head()

,property_type,society,sector,price,price_per_sqft,bedRoom,bathroom,balcony,floorNum,agePossession,property_id,builtup_area,study room,pooja room,store room,servant room,others,furnishing_type,facility_score
0,house,independent,sector 25,4.35,32222.0,5,4,3,3.0,Old Property,R70162684,1350.0,0,0,0,1,0,0,49
1,flat,the close south,sector 50,3.10,12444.0,3,4,3+,4.0,Moderately Old,H69433380,2450.0,0,0,0,1,0,2,165
2,flat,signature global city 63a,sector 63a,1.65,15263.0,2,2,2,1.0,Under Construction,G69165782,978.0,0,0,0,0,0,0,0
3,flat,saan verdante,sector 95,2.00,10178.0,3,4,3+,5.0,New Property,U70096330,1964.0,0,0,0,1,0,0,49
4,flat,puri diplomatic greens,sector 111,3.90,13000.0,4,5,3+,6.0,Relatively New,S69742910,2996.0,0,0,0,1,0,1,160

In [5]:
# undoing the conversion of numeric columns to categorical
df['furnishing_type'].value_counts()

furnishing_type
0    2367
2     989
1     186
Name: count, dtype: int64

In [6]:
df['furnishing_type'] = df['furnishing_type'].replace({0.0: 'unfurnished', 1.0: 'semi-furnished', 2.0: 'furnished'})

In [7]:
df.head()

,property_type,society,sector,price,price_per_sqft,bedRoom,bathroom,balcony,floorNum,agePossession,property_id,builtup_area,study room,pooja room,store room,servant room,others,furnishing_type,facility_score
0,house,independent,sector 25,4.35,32222.0,5,4,3,3.0,Old Property,R70162684,1350.0,0,0,0,1,0,unfurnished,49
1,flat,the close south,sector 50,3.10,12444.0,3,4,3+,4.0,Moderately Old,H69433380,2450.0,0,0,0,1,0,furnished,165
2,flat,signature global city 63a,sector 63a,1.65,15263.0,2,2,2,1.0,Under Construction,G69165782,978.0,0,0,0,0,0,unfurnished,0
3,flat,saan verdante,sector 95,2.00,10178.0,3,4,3+,5.0,New Property,U70096330,1964.0,0,0,0,1,0,unfurnished,49
4,flat,puri diplomatic greens,sector 111,3.90,13000.0,4,5,3+,6.0,Relatively New,S69742910,2996.0,0,0,0,1,0,semi-furnished,160

In [8]:
def categorize_facility_score(score):
    if(0 <= score < 50):
        return "Low"
    elif(50 <= score < 150):
        return "Medium"
    elif 150 <= score < 175:
        return "High"
    else:
        return None
    
df['facility_category'] = df['facility_score'].apply(categorize_facility_score)

In [9]:
df.head()

,property_type,society,sector,price,price_per_sqft,bedRoom,bathroom,balcony,floorNum,agePossession,property_id,builtup_area,study room,pooja room,store room,servant room,others,furnishing_type,facility_score,facility_category
0,house,independent,sector 25,4.35,32222.0,5,4,3,3.0,Old Property,R70162684,1350.0,0,0,0,1,0,unfurnished,49,Low
1,flat,the close south,sector 50,3.10,12444.0,3,4,3+,4.0,Moderately Old,H69433380,2450.0,0,0,0,1,0,furnished,165,High
2,flat,signature global city 63a,sector 63a,1.65,15263.0,2,2,2,1.0,Under Construction,G69165782,978.0,0,0,0,0,0,unfurnished,0,Low
3,flat,saan verdante,sector 95,2.00,10178.0,3,4,3+,5.0,New Property,U70096330,1964.0,0,0,0,1,0,unfurnished,49,Low
4,flat,puri diplomatic greens,sector 111,3.90,13000.0,4,5,3+,6.0,Relatively New,S69742910,2996.0,0,0,0,1,0,semi-furnished,160,High

In [10]:
def floor_range(floor):
    if 0 <= floor <= 2:
        return "Low Floor"
    elif 3 <= floor <= 10:
        return "Mid Floor"
    elif 11 <= floor <= 51:
        return "High Floor"
    else:
        return None

df['floor_category'] = df['floorNum'].apply(floor_range)

In [11]:
df.head()

,property_type,society,sector,price,price_per_sqft,bedRoom,bathroom,balcony,floorNum,agePossession,...,builtup_area,study room,pooja room,store room,servant room,others,furnishing_type,facility_score,facility_category,floor_category
0,house,independent,sector 25,4.35,32222.0,5,4,3,3.0,Old Property,...,1350.0,0,0,0,1,0,unfurnished,49,Low,Mid Floor
1,flat,the close south,sector 50,3.10,12444.0,3,4,3+,4.0,Moderately Old,...,2450.0,0,0,0,1,0,furnished,165,High,Mid Floor
2,flat,signature global city 63a,sector 63a,1.65,15263.0,2,2,2,1.0,Under Construction,...,978.0,0,0,0,0,0,unfurnished,0,Low,Low Floor
3,flat,saan verdante,sector 95,2.00,10178.0,3,4,3+,5.0,New Property,...,1964.0,0,0,0,1,0,unfurnished,49,Low,Mid Floor
4,flat,puri diplomatic greens,sector 111,3.90,13000.0,4,5,3+,6.0,Relatively New,...,2996.0,0,0,0,1,0,semi-furnished,160,High,Mid Floor

In [12]:
X = df.drop(columns=['society', 'price_per_sqft', 'facility_score', 'floorNum', 'price', 'property_id', 'others', 'study room'])
y = df['price']

In [13]:
X.head()

,property_type,sector,bedRoom,bathroom,balcony,agePossession,builtup_area,pooja room,store room,servant room,furnishing_type,facility_category,floor_category
0,house,sector 25,5,4,3,Old Property,1350.0,0,0,1,unfurnished,Low,Mid Floor
1,flat,sector 50,3,4,3+,Moderately Old,2450.0,0,0,1,furnished,High,Mid Floor
2,flat,sector 63a,2,2,2,Under Construction,978.0,0,0,0,unfurnished,Low,Low Floor
3,flat,sector 95,3,4,3+,New Property,1964.0,0,0,1,unfurnished,Low,Mid Floor
4,flat,sector 111,4,5,3+,Relatively New,2996.0,0,0,1,semi-furnished,High,Mid Floor

In [14]:
y_transformed = np.log1p(y) # log transformation to reduce skewness

### Ordinal Encoding

In [15]:
cols_to_encode = ['property_type', 'sector', 'balcony', 'agePossession', 'furnishing_type', 'facility_category', 'floor_category']

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder
preprocessor = ColumnTransformer(
    transformers = [
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'builtup_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cols_to_encode)
    ],
    remainder='passthrough'
)

In [17]:
# pipeline creation
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', LinearRegression())
])

In [18]:
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=15, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kf, scoring='r2')

In [19]:
scores.mean(), scores.std()

(np.float64(0.7371388044887094), np.float64(0.03525757877289752))

In [20]:
scores

array([0.67954656, 0.78560682, 0.68106271, 0.7414383 , 0.71854986,
       0.73822906, 0.72876986, 0.77704499, 0.78388394, 0.69289196,
       0.76712143, 0.74757864, 0.76033011, 0.75861207, 0.69641576])

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y_transformed, test_size=0.2, random_state=42)

In [22]:
pipeline.fit(X_train, y_train)

d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'builtup_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'facility_category',
                                                   'floor_category'])])),
                ('regressor', LinearRegression())])

In [23]:
y_pred = pipeline.predict(X_test)
y_pred = np.expm1(y_pred)  # inverse log transformation

In [24]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(np.expm1(y_test), y_pred)
mae

0.9651871271664929

In [25]:
# function to test each algorithm
def testing(model_name, model):
    output = []
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # kfolds
    kf = KFold(n_splits=15, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kf, scoring='r2')
    
    output.append(scores.mean())
    
    # fit the model
    X_train, X_test, y_train, y_test = train_test_split(X, y_transformed, test_size=0.2, random_state=42)
    pipeline.fit(X_train, y_train)
    
    y_pred = pipeline.predict(X_test)
    y_pred = np.expm1(y_pred)  # inverse log transformation
    
    output.append(mean_absolute_error(np.expm1(y_test), y_pred))
    return output

In [50]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, AdaBoostRegressor, ExtraTreesRegressor
from xgboost import XGBRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.svm import SVR

models_dict = {
    'linear_regression': LinearRegression(),
    'svr': SVR(),
    'ridge': Ridge(),
    'lasso': Lasso(),
    'decision_tree': DecisionTreeRegressor(),
    'random_forest': RandomForestRegressor(),
    'gradient_boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'xgboost': XGBRegressor(),
    'mlp': MLPRegressor(), # multi layer perceptron neural network
    'extra_trees': ExtraTreesRegressor()
}

In [27]:
model_output = []
for model_name, model in models_dict.items():
    output = testing(model_name, model)
    model_output.append(output)
    
model_output

d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

[['linear_regression', np.float64(0.7371388044887094), 0.9651871271664929],
 ['svr', np.float64(0.7605220880680996), 0.8820495297956371],
 ['ridge', np.float64(0.7371427158180014), 0.9650741140093893],
 ['lasso', np.float64(0.05267806571383358), 1.5360692413664065],
 ['decision_tree', np.float64(0.7749516242027316), 0.7041979438266974],
 ['random_forest', np.float64(0.8825299217418252), 0.5370966994735245],
 ['gradient_boosting', np.float64(0.8725233844285795), 0.559204443807995],
 ['adaboost', np.float64(0.750391191774533), 0.835190037285175],
 ['xgboost', np.float64(0.8893686074131699), 0.5119956820059899],
 ['mlp', np.float64(0.7975868030274388), 0.8481742354841506]]

In [28]:
pd.DataFrame(model_output, columns=['name', 'r2', 'mae']).sort_values(['mae'])

                name        r2       mae
8            xgboost  0.889369  0.511996
5      random_forest  0.882530  0.537097
6  gradient_boosting  0.872523  0.559204
4      decision_tree  0.774952  0.704198
7           adaboost  0.750391  0.835190
9                mlp  0.797587  0.848174
1                svr  0.760522  0.882050
2              ridge  0.737143  0.965074
0  linear_regression  0.737139  0.965187
3              lasso  0.052678  1.536069

### One Hot Encoding

In [36]:
from sklearn.preprocessing import OneHotEncoder
ohe_preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'builtup_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cols_to_encode), # categorical cols where order matters
        ('cat01', OneHotEncoder(handle_unknown='ignore'), ['sector', 'agePossession', 'furnishing_type'])
    ],
    remainder='passthrough'
)

In [37]:
ohe_pipeline = Pipeline([
    ('preprocessor', ohe_preprocessor),
    ('regressor', LinearRegression())
])

In [38]:
kfold = KFold(n_splits=15, shuffle=True, random_state=42)
ohe_scores = cross_val_score(ohe_pipeline, X, y_transformed, cv=kfold, scoring='r2')

In [39]:
ohe_scores.mean()

np.float64(0.8584620691647216)

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y_transformed, test_size=0.2, random_state=42)
ohe_pipeline.fit(X_train, y_train)

d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'builtup_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'facility_category',
                                                   'floor_category']),
                                                 ('cat01',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['sector', 'agePossession',
                                                   'furnishing_type'])])),
                ('regressor', LinearRegression())])

In [41]:
y_pred = ohe_pipeline.predict(X_test)
y_pred = np.expm1(y_pred)  # inverse log transformation

In [ ]:
mean_absolute_error(np.expm1(y_test), y_pred)

0.6677121504428858

In [43]:
def testing_ohe(model_name, model):
    output = []
    output.append(model_name)
    
    ohe_pipeline = Pipeline([
        ('preprocessor', ohe_preprocessor),
        ('regressor', model)
    ])
    
    # kfolds
    kfold = KFold(n_splits=15, shuffle=True, random_state=42)
    scores = cross_val_score(ohe_pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    # fit the model
    X_train, X_test, y_train, y_test = train_test_split(X, y_transformed, test_size=0.2, random_state=42)
    ohe_pipeline.fit(X_train, y_train)
    
    y_pred = ohe_pipeline.predict(X_test)
    y_pred = np.expm1(y_pred)  # inverse log transformation
    
    output.append(mean_absolute_error(np.expm1(y_test), y_pred))
    return output

In [44]:
ohe_model_output = []
for model_name, model in models_dict.items():
    output = testing_ohe(model_name, model)
    ohe_model_output.append(output)

In [45]:
pd.DataFrame(ohe_model_output, columns=['name', 'r2', 'mae']).sort_values(['mae'])

                name        r2       mae
8            xgboost  0.897724  0.491176
5      random_forest  0.892266  0.498434
6  gradient_boosting  0.875387  0.531967
9                mlp  0.865424  0.637804
4      decision_tree  0.808068  0.657965
0  linear_regression  0.858462  0.667712
2              ridge  0.858537  0.674091
7           adaboost  0.752114  0.791816
1                svr  0.764664  0.875771
3              lasso  0.052678  1.536069

here also linear models didn't perform well because dimensionality is very high and if we see they have performed better than previous one if we compare.

### OHE with PCA

In [46]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'builtup_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cols_to_encode), # categorical cols where order matters
        ('cat01', OneHotEncoder(handle_unknown='ignore'), ['sector', 'agePossession', 'furnishing_type'])
    ],
    remainder='passthrough'
)

In [48]:
from sklearn.decomposition import PCA

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('pca', PCA(n_components=.95)),
    ('regressor', LinearRegression())
])

In [49]:
kfold = KFold(n_splits=15, shuffle=True, random_state=42)
scores = cross_val_score(ohe_pipeline, X, y_transformed, cv=kfold, scoring='r2')

scores.mean()

np.float64(0.8584620691647216)

In [65]:
# function to test each algorithm
def scorer(model_name, model):
    
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('pca', PCA(n_components=0.95)),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X,y_transformed,test_size=0.2,random_state=42)
    
    pipeline.fit(X_train,y_train)
    
    y_pred = pipeline.predict(X_test)
    
    y_pred = np.expm1(y_pred)
    
    output.append(mean_absolute_error(np.expm1(y_test),y_pred))
    
    return output

In [66]:
model_dict = {
    'linear_reg':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'LASSO':Lasso(),
    'decision tree': DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'extra trees': ExtraTreesRegressor(),
    'gradient boosting': GradientBoostingRegressor(),
    'adaboost': AdaBoostRegressor(),
    'mlp': MLPRegressor(),
    'xgboost':XGBRegressor()
}

In [ ]:
model_output = []
for model_name,model in model_dict.items():
    model_output.append(scorer(model_name, model))

dimensionality reduction didn't worked here. don't know why the accuracy decreased need to analyze it after.

### target encoding

when high dimensional data is present, we use target encoding.  
it encodes the categorical values based on the target (price) variable.

get to the documentation for better understanding.

In [69]:
import category_encoders as ce

cols_to_encode = ['property_type', 'sector', 'balcony', 'agePossession', 'furnishing_type', 'facility_category', 'floor_category']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'builtup_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cols_to_encode),
        ('cat1', OneHotEncoder(handle_unknown='ignore', drop='first', sparse_output=False), ['agePossession']),   
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ],
    remainder='passthrough'
)

In [70]:
pipeline = Pipeline(
    [
        ('preprocessor', preprocessor),
        ('regressor', LinearRegression())
    ]
)

In [71]:
kfold = KFold(n_splits=15, shuffle=True, random_state=42)
scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')

scores.mean(), scores.std()

(np.float64(0.830014330320065), np.float64(0.030692123276420635))

In [72]:
def scorer(model_name, model):
    output = []
    
    output.append(model_name)
    
    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])
    
    # K-fold cross-validation
    kfold = KFold(n_splits=10, shuffle=True, random_state=42)
    scores = cross_val_score(pipeline, X, y_transformed, cv=kfold, scoring='r2')
    output.append(scores.mean())
    
    X_train, X_test, y_train, y_test = train_test_split(X, y_transformed, test_size=0.2, random_state=42)
    pipeline.fit(X_train, y_train)
    
    y_pred = pipeline.predict(X_test)
    y_pred = np.expm1(y_pred)  # inverse log transformation
    
    
    output.append(mean_absolute_error(np.expm1(y_test), y_pred))
    return output

In [73]:
model_output = []
for model_name, model in model_dict.items():
    output = scorer(model_name, model)
    model_output.append(output)

pd.DataFrame(model_output, columns=['name', 'r2', 'mae']).sort_values(['mae']).sort_values(['mae'])

                 name        r2       mae
5       random forest  0.902554  0.500149
6         extra trees  0.900611  0.500706
10            xgboost  0.898605  0.502882
7   gradient boosting  0.887343  0.543590
4       decision tree  0.828242  0.687614
9                 mlp  0.842531  0.691294
0          linear_reg  0.830611  0.773333
2               ridge  0.830630  0.773655
8            adaboost  0.812034  0.778215
1                 svr  0.775909  0.864390
3               LASSO  0.053468  1.536069

target encoding works better on tree based models.  
slight improvements but not on linear models.

### Hyperparameter Tuning

In [ ]:
from sklearn.model_selection import GridSearchCV

# tuning random forest first
param_grid = {
    'regressor__n_estimators': [50, 100, 200, 300],
    'regressor__max_depth': [None, 5, 10, 15, 20, 30],
    'regressor__max_samples': [.1, .25, .5, .75, 1.0],
    'regressor__max_features': ['auto', 'sqrt']
}

In [79]:
cols_to_encode = ['property_type', 'sector', 'balcony', 'agePossession', 'furnishing_type', 'facility_category', 'floor_category']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'builtup_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cols_to_encode),
        ('cat1', OneHotEncoder(handle_unknown='ignore', drop='first', sparse_output=False), ['agePossession']),   
        ('target_enc', ce.TargetEncoder(), ['sector'])
    ],
    remainder='passthrough'
)

In [80]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(random_state=42))
])

In [81]:
kfold = KFold(n_splits=15, shuffle=True, random_state=42)
search = GridSearchCV(pipeline, param_grid, cv=kfold, scoring='r2', n_jobs=-1, verbose=4)

In [82]:
search.fit(X, y_transformed)

Fitting 15 folds for each of 240 candidates, totalling 3600 fits

d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
1800 fits failed out of a total of 3600.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1117 fits failed with the following error:
Traceback (most recent call last):
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\pipeline.py", line 662, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
683 fits failed with the following error:
Traceback (most recent call last):
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\pipeline.py", line 662, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.86737676 0.8691851  0.86869752 0.86858532
 0.88301325 0.88472767 0.88525032 0.8856184  0.88980621 0.89216882
 0.89276249 0.89354642 0.8949187  0.89617867 0.89641526 0.89726747
 0.89550143 0.8980303  0.89871935 0.89912219        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.83840995 0.83887599 0.83868611 0.83798472 0.84198215 0.84192186
 0.84161419 0.84115033 0.84513803 0.84387035 0.84273642 0.84219753
 0.84352416 0.84341062 0.84278537 0.84214868 0.84244148 0.84279688
 0.84248233 0.84211559        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.86759446 0.86872544
 0.86807655 0.86772506 0.87658412 0.879746   0.88029823 0.88045363
 0.88664095 0.8873948  0.88640526 0.88644466 0.88809712 0.88896884
 0.88894521 0.88904056 0.88829926 0.89013793 0.89023689 0.89056695
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.86459092 0.86797046 0.86882804 0.86849006
 0.88138363 0.88316818 0.88310635 0.88378593 0.88924592 0.89108559
 0.89158715 0.89215742 0.89442347 0.89660537 0.89647957 0.89700279
 0.89583112 0.89712357 0.89773097 0.89788854        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.86663076 0.86867172 0.86858174 0.86853435 0.8814075  0.8825098
 0.88380252 0.88434889 0.89092538 0.89234118 0.89224784 0.89305232
 0.89421207 0.89618364 0.89654995 0.89702387 0.89583295 0.89821124
 0.89870837 0.89910701        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.86737676 0.8691851
 0.86869752 0.86858532 0.88301325 0.88472767 0.88525032 0.8856184
 0.88976702 0.89214049 0.8927479  0.89352419 0.89504146 0.89627569
 0.89647493 0.89731453 0.89546999 0.89797292 0.89857293 0.89897822]
  warnings.warn(
d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

GridSearchCV(cv=KFold(n_splits=15, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['bedRoom',
                                                                          'bathroom',
                                                                          'builtup_area',
                                                                          'servant '
                                                                          'room',
                                                                          'store '
                                                                          'room']),
                                                                        ('cat',
                                                                         OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                        unknown_value=-1),
                                                                         ['property_type',
                                                                          'se...
                                                                                       sparse_output=False),
                                                                         ['agePossession']),
                                                                        ('target_enc',
                                                                         TargetEncoder(),
                                                                         ['sector'])])),
                                       ('regressor',
                                        RandomForestRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'regressor__max_depth': [None, 5, 10, 15, 20, 30],
                         'regressor__max_features': ['auto', 'sqrt'],
                         'regressor__max_samples': [0.1, 0.25, 0.5, 0.75, 1.0],
                         'regressor__n_estimators': [50, 100, 200, 300]},
             scoring='r2', verbose=4)

In [83]:
final_pipe = search.best_estimator_
search.best_params_

{'regressor__max_depth': None,
 'regressor__max_features': 'sqrt',
 'regressor__max_samples': 1.0,
 'regressor__n_estimators': 300}

In [ ]:
search.best_score_

np.float64(0.8991221947784958)

In [85]:
final_pipe.fit(X, y_transformed)

d:\Projects\capstone-project\myenv\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'builtup_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'facility_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['agePossession']),
                                                 ('target_enc', TargetEncoder(),
                                                  ['sector'])])),
                ('regressor',
                 RandomForestRegressor(max_features='sqrt', max_samples=1.0,
                                       n_estimators=300, random_state=42))])

not much improvement, skipping it.

## Exporting

In [86]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['bedRoom', 'bathroom', 'builtup_area', 'servant room', 'store room']),
        ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cols_to_encode),
        ('cat1', OneHotEncoder(handle_unknown='ignore', drop='first', sparse_output=False), ['agePossession', 'sector'])
    ]
)

In [87]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(n_estimators=500))
])

In [88]:
pipeline.fit(X, y_transformed)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['bedRoom', 'bathroom',
                                                   'builtup_area',
                                                   'servant room',
                                                   'store room']),
                                                 ('cat',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  ['property_type', 'sector',
                                                   'balcony', 'agePossession',
                                                   'furnishing_type',
                                                   'facility_category',
                                                   'floor_category']),
                                                 ('cat1',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['agePossession',
                                                   'sector'])])),
                ('regressor', RandomForestRegressor(n_estimators=500))])

In [89]:
import pickle

with open('../models/pipeline.pkl', 'wb') as file:
    pickle.dump(pipeline, file)

In [90]:
with open('../models/df.pkl', 'wb') as file:
    pickle.dump(X, file)

### Unseen Data Prediction

In [ ]:
X.columns

Index(['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony',
       'agePossession', 'builtup_area', 'pooja room', 'store room',
       'servant room', 'furnishing_type', 'facility_category',
       'floor_category'],
      dtype='object')

In [92]:
data = [['house', 'sector 49', 3, 3, '3+', 'New Property', 1750, 0, 0, 'unfurnished', 'Low', "Low Floor"]]
columns = ['property_type', 'sector', 'bedRoom', 'bathroom', 'balcony', 'agePossession', 'builtup_area', 'servant room', 'store room', 'furnishing_type', 'facility_category', 'floor_category']

new_df = pd.DataFrame(data, columns=columns)
new_df.head()

,property_type,sector,bedRoom,bathroom,balcony,agePossession,builtup_area,servant room,store room,furnishing_type,facility_category,floor_category
0,house,sector 49,3,3,3+,New Property,1750,0,0,unfurnished,Low,Low Floor

In [93]:
np.expm1(pipeline.predict(new_df))

array([2.76114466])

it was a real property, and it's correct price was 2.5..  
very close but can improve, betting on xgboost