In [2]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('../datasets/final_dataset_missing_value_imputed_v5.csv').drop(columns=['store room', 'society', 'price_per_sqft', 'balcony', 'property_id', 'study room', 'pooja room', 'others'])
df.head()

,property_type,sector,price,bedRoom,bathroom,floorNum,agePossession,builtup_area,servant room,furnishing_type,facility_score
0,house,sector 25,4.35,5,4,3.0,Old Property,1350.0,1,0,49
1,flat,sector 50,3.10,3,4,4.0,Moderately Old,2450.0,1,2,165
2,flat,sector 63a,1.65,2,2,1.0,Under Construction,978.0,0,0,0
3,flat,sector 95,2.00,3,4,5.0,New Property,1964.0,1,0,49
4,flat,sector 111,3.90,4,5,6.0,Relatively New,2996.0,1,1,160

will perform linear regression to gain the relation knowlede.

In [4]:
# numerical - bedRoom, bathroom, builtup_area, servant_room
# ordinal - property_type, furnishing_type, luxury_category
# ohe - sector, agePossession

In [5]:
df['agePossession'].value_counts()

agePossession
Relatively New        1723
Moderately Old         618
New Property           595
Old Property           330
Under Construction     276
Name: count, dtype: int64

value counts has 5 types reducing them to 3: old, new, under construction

In [6]:
df['agePossession'].replace({
    'Relatively New': 'new',
    'Moderately Old': 'old',
    'New Property': 'new',
    'Old Property': 'old',
    'Under Construction': 'under_construction',
}, inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_18824\80852311.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['agePossession'].replace({

In [7]:
df['agePossession'].value_counts()

agePossession
new                   2318
old                    948
under_construction     276
Name: count, dtype: int64

In [8]:
df.head()

,property_type,sector,price,bedRoom,bathroom,floorNum,agePossession,builtup_area,servant room,furnishing_type,facility_score
0,house,sector 25,4.35,5,4,3.0,old,1350.0,1,0,49
1,flat,sector 50,3.10,3,4,4.0,old,2450.0,1,2,165
2,flat,sector 63a,1.65,2,2,1.0,under_construction,978.0,0,0,0
3,flat,sector 95,2.00,3,4,5.0,new,1964.0,1,0,49
4,flat,sector 111,3.90,4,5,6.0,new,2996.0,1,1,160

In [9]:
df['property_type'].replace({
    'flat': 0,
    'house': 1
}, inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_18824\1548980210.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['property_type'].replace({
C:\Users\hp\AppData\Local\Temp\ipykernel_18824\1548980210.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['property_type'].replace({

In [10]:
def categorize_facility_score(score):
    if(0 <= score < 50):
        return "Low"
    elif(50 <= score < 150):
        return "Medium"
    elif 150 <= score < 175:
        return "High"
    else:
        return None

# converting facility_score to categorical values
df['facility_category'] = df['facility_score'].apply(categorize_facility_score)
df.drop(columns=['facility_score'], inplace=True)

# converting facility_category to numerical values
df['facility_category'].replace({
    'Low': 0,
    'Medium': 1,
    'High': 2
}, inplace=True)

df.head()

C:\Users\hp\AppData\Local\Temp\ipykernel_18824\3250177137.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facility_category'].replace({
C:\Users\hp\AppData\Local\Temp\ipykernel_18824\3250177137.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['facility_category'].replace({

,property_type,sector,price,bedRoom,bathroom,floorNum,agePossession,builtup_area,servant room,furnishing_type,facility_category
0,1,sector 25,4.35,5,4,3.0,old,1350.0,1,0,0
1,0,sector 50,3.10,3,4,4.0,old,2450.0,1,2,2
2,0,sector 63a,1.65,2,2,1.0,under_construction,978.0,0,0,0
3,0,sector 95,2.00,3,4,5.0,new,1964.0,1,0,0
4,0,sector 111,3.90,4,5,6.0,new,2996.0,1,1,2

In [11]:
new_df = pd.get_dummies(df, columns=['sector', 'agePossession'], drop_first=True)
new_df.head()

,property_type,price,bedRoom,bathroom,floorNum,builtup_area,servant room,furnishing_type,facility_category,sector_gwal pahari,sector_manesar,sector_new,sector_new sector 2,sector_sector 1,sector_sector 102,sector_sector 103,sector_sector 104,sector_sector 105,sector_sector 106,sector_sector 107,sector_sector 108,sector_sector 109,sector_sector 10a,sector_sector 11,sector_sector 110,sector_sector 111,sector_sector 112,sector_sector 113,sector_sector 12,sector_sector 13,sector_sector 14,sector_sector 15,sector_sector 17,sector_sector 17a,sector_sector 17b,sector_sector 2,sector_sector 21,sector_sector 22,sector_sector 23,sector_sector 24,sector_sector 25,sector_sector 26,sector_sector 27,sector_sector 28,sector_sector 3,sector_sector 3 phase 2,sector_sector 3 phase 3 extension,sector_sector 30,sector_sector 31,sector_sector 33,sector_sector 36,sector_sector 36a,sector_sector 37,sector_sector 37c,sector_sector 37d,sector_sector 38,sector_sector 39,sector_sector 4,sector_sector 40,sector_sector 41,sector_sector 43,sector_sector 45,sector_sector 46,sector_sector 47,sector_sector 48,sector_sector 49,sector_sector 5,sector_sector 50,sector_sector 51,sector_sector 52,sector_sector 53,sector_sector 54,sector_sector 55,sector_sector 56,sector_sector 57,sector_sector 58,sector_sector 59,sector_sector 6,sector_sector 60,sector_sector 61,sector_sector 62,sector_sector 63,sector_sector 63a,sector_sector 65,sector_sector 66,sector_sector 67,sector_sector 67a,sector_sector 68,sector_sector 69,sector_sector 7,sector_sector 70,sector_sector 70a,sector_sector 71,sector_sector 72,sector_sector 73,sector_sector 74,sector_sector 76,sector_sector 77,sector_sector 78,sector_sector 79,sector_sector 8,sector_sector 80,sector_sector 81,sector_sector 82,sector_sector 82a,sector_sector 83,sector_sector 84,sector_sector 85,sector_sector 86,sector_sector 88a,sector_sector 88b,sector_sector 89,sector_sector 9,sector_sector 90,sector_sector 91,sector_sector 92,sector_sector 93,sector_sector 95,sector_sector 99,sector_sector 99a,sector_sector 9a,sector_sohna road,sector_sohna road road,agePossession_old,agePossession_under_construction
0,1,4.35,5,4,3.0,1350.0,1,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
1,0,3.10,3,4,4.0,2450.0,1,2,2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
2,0,1.65,2,2,1.0,978.0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,0,2.00,3,4,5.0,1964.0,1,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
4,0,3.90,4,5,6.0,2996.0,1,1,2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
X = new_df.drop(columns=['price'])
y = new_df['price']
y_log = np.log1p(y) # it was right skewed, so we apply log transformation

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

X_scaled.head()

,property_type,bedRoom,bathroom,floorNum,builtup_area,servant room,furnishing_type,facility_category,sector_gwal pahari,sector_manesar,sector_new,sector_new sector 2,sector_sector 1,sector_sector 102,sector_sector 103,sector_sector 104,sector_sector 105,sector_sector 106,sector_sector 107,sector_sector 108,sector_sector 109,sector_sector 10a,sector_sector 11,sector_sector 110,sector_sector 111,sector_sector 112,sector_sector 113,sector_sector 12,sector_sector 13,sector_sector 14,sector_sector 15,sector_sector 17,sector_sector 17a,sector_sector 17b,sector_sector 2,sector_sector 21,sector_sector 22,sector_sector 23,sector_sector 24,sector_sector 25,sector_sector 26,sector_sector 27,sector_sector 28,sector_sector 3,sector_sector 3 phase 2,sector_sector 3 phase 3 extension,sector_sector 30,sector_sector 31,sector_sector 33,sector_sector 36,sector_sector 36a,sector_sector 37,sector_sector 37c,sector_sector 37d,sector_sector 38,sector_sector 39,sector_sector 4,sector_sector 40,sector_sector 41,sector_sector 43,sector_sector 45,sector_sector 46,sector_sector 47,sector_sector 48,sector_sector 49,sector_sector 5,sector_sector 50,sector_sector 51,sector_sector 52,sector_sector 53,sector_sector 54,sector_sector 55,sector_sector 56,sector_sector 57,sector_sector 58,sector_sector 59,sector_sector 6,sector_sector 60,sector_sector 61,sector_sector 62,sector_sector 63,sector_sector 63a,sector_sector 65,sector_sector 66,sector_sector 67,sector_sector 67a,sector_sector 68,sector_sector 69,sector_sector 7,sector_sector 70,sector_sector 70a,sector_sector 71,sector_sector 72,sector_sector 73,sector_sector 74,sector_sector 76,sector_sector 77,sector_sector 78,sector_sector 79,sector_sector 8,sector_sector 80,sector_sector 81,sector_sector 82,sector_sector 82a,sector_sector 83,sector_sector 84,sector_sector 85,sector_sector 86,sector_sector 88a,sector_sector 88b,sector_sector 89,sector_sector 9,sector_sector 90,sector_sector 91,sector_sector 92,sector_sector 93,sector_sector 95,sector_sector 99,sector_sector 99a,sector_sector 9a,sector_sohna road,sector_sohna road road,agePossession_old,agePossession_under_construction
0,1.942572,1.561377,0.521101,-0.641426,-0.428495,1.339993,-0.684726,-0.985377,-0.069446,-0.093965,-0.033624,-0.037598,-0.041193,-0.176493,-0.109545,-0.138855,-0.075356,-0.104138,-0.130152,-0.129025,-0.157747,-0.044499,-0.067363,-0.080845,-0.079057,-0.080845,-0.110857,-0.095482,-0.047579,-0.071469,-0.041193,-0.041193,-0.016805,-0.029115,-0.132377,-0.041193,-0.075356,-0.060694,-0.075356,10.009995,-0.105515,-0.023769,-0.102744,-0.082596,-0.041193,-0.050472,-0.037598,-0.05321,-0.138855,-0.055815,-0.055815,-0.016805,-0.120868,-0.134568,-0.05321,-0.055815,-0.113438,-0.037598,-0.055815,-0.126745,-0.047579,-0.055815,-0.067363,-0.12559,-0.112154,-0.041193,-0.131269,-0.044499,-0.062994,-0.062994,-0.085993,-0.05321,-0.12325,-0.077228,-0.044499,-0.047579,-0.055815,-0.065214,-0.108217,-0.067363,-0.062994,-0.065214,-0.156805,-0.108217,-0.115965,-0.077228,-0.092424,-0.164208,-0.0999,-0.11844,-0.124425,-0.087643,-0.090857,-0.029115,-0.071469,-0.065214,-0.085993,-0.067363,-0.148079,-0.044499,-0.037598,-0.158685,-0.108217,-0.073438,-0.139907,-0.11844,-0.176493,-0.133477,-0.077228,-0.029115,-0.12789,-0.058305,-0.159617,-0.069446,-0.16957,-0.047579,-0.125590,-0.058305,-0.092424,-0.05321,-0.211749,-0.055815,1.654173,-0.290701
1,-0.514782,-0.067366,0.521101,-0.476411,0.527050,1.339993,1.556770,1.863770,-0.069446,-0.093965,-0.033624,-0.037598,-0.041193,-0.176493,-0.109545,-0.138855,-0.075356,-0.104138,-0.130152,-0.129025,-0.157747,-0.044499,-0.067363,-0.080845,-0.079057,-0.080845,-0.110857,-0.095482,-0.047579,-0.071469,-0.041193,-0.041193,-0.016805,-0.029115,-0.132377,-0.041193,-0.075356,-0.060694,-0.075356,-0.099900,-0.105515,-0.023769,-0.102744,-0.082596,-0.041193,-0.050472,-0.037598,-0.05321,-0.138855,-0.055815,-0.055815,-0.016805,-0.120868,-0.134568,-0.05321,-0.055815,-0.113438,-0.037598,-0.055815,-0.126745,-0.047579,-0.055815,-0.067363,-0.12559,-0.112154,-0.041193,7.617961,-0.044499,-0.062994,-0.062994,-0.085993,-0.05321,-0.12325,-0.077228,-0.044499,-0.047579,-0.055815,-0.065214,-0.108217,-0.067363,-0.062994,-0.065214,-0.156805,-0.108217,-0.115965,-0.077228,-0.092424,-0.164208,-0.0999,-0.11844,-0.124425,-0.087643,-0.090857,-0.029115,-0.071469,-0.065214,-0.085993,-0.067363,-0.148079,-0.044499,-0.037598,-0.158685,-0.108217,-0.073438,-0.139907,-0.11844,-0.176493,-0.133477,-0.077228,-0.029115,-0.12789,-0.058305,-0.159617,-0.069446,-0.16957,-0.047579,-0.125590,-0.058305,-0.092424,-0.05321,-0.211749,-0.055815,1.654173,-0.290701
2,-0.514782,-0.881738,-0.877186,-0.971457,-0.751642,-0.746273,-0.684726,-0.985377,-0.069446,-0.093965,-0.033624,-0.037598,-0.041193,-0.176493,-0.109545,-0.138855,-0.075356,-0.104138,-0.130152,-0.129025,-0.157747,-0.044499,-0.067363,-0.080845,-0.079057,-0.080845,-0.110857,-0.095482,-0.047579,-0.071469,-0.041193,-0.041193,-0.016805,-0.029115,-0.132377,-0.041193,-0.075356,-0.060694,-0.075356,-0.099900,-0.105515,-0.023769,-0.102744,-0.082596,-0.041193,-0.050472,-0.037598,-0.05321,-0.138855,-0.055815,-0.055815,-0.016805,-0.120868,-0.134568,-0.05321,-0.055815,-0.113438,-0.037598,-0.055815,-0.126745,-0.047579,-0.055815,-0.067363,-0.12559,-0.112154,-0.041193,-0.131269,-0.044499,-0.062994,-0.062994,-0.085993,-0.05321,-0.12325,-0.077228,-0.044499,-0.047579,-0.055815,-0.065214,-0.108217,-0.067363,-0.062994,15.334058,-0.156805,-0.108217,-0.115965,-0.077228,-0.092424,-0.164208,-0.0999,-0.11844,-0.124425,-0.087643,-0.090857,-0.029115,-0.071469,-0.065214,-0.085993,-0.067363,-0.148079,-0.044499,-0.037598,-0.158685,-0.108217,-0.073438,-0.139907,-0.11844,-0.176493,-0.133477,-0.077228,-0.029115,-0.12789,-0.058305,-0.159617,-0.069446,-0.16957,-0.047579,-0.125590,-0.058305,-0.092424,-0.05321,-0.211749,-0.055815,-0.604532,3.439961
3,-0.514782,-0.067366,0.521101,-0.311395,0.104873,1.339993,-0.684726,-0.985377,-0.069446,-0.093965,-0.033624,-0.037598,-0.041193,-0.176493,-0.109545,-0.138855,-0.075356,-0.104138,-0.130152,-0.129025,-0.157747,-0.044499,-0.067363,-0.080845,-0.079057,-0.080845,-0.110857,-0.095482,-0.047579,-0.071469,-0.041193,-0.041193,-0.016805,-0.029115,-0.132377,-0.041193,-0.075356,-0.060694,-0.075356,-0.099900,-0.105515,-0.023769,-0.102744,-0.082596,-0.041193,-0.050472,-0.037598,-0.05321,-0.138855,-0.055815,-0.055815,-0.016805,-0.120868,-0.134568,-0.05321,-0.055815,-0.113438,-0.037598,-0.055815,-0.126745,-0.047579,-0.055815,-0.067363,-0.12559,-0.112154,-0.041193,-0.131269,-0.044499,-0.062994,-0.062994,-0.085993,-0.05321,-0.12325,-0.077228,-0.044499,-0.047579,-0.055815,-0.065214,-0.108217,-0.067363,-0.062994,-0.065214,-0.156805,-0.108217,-0.115965,-0.077228,-0.092424,-0.164208,-0.0999,-0.11844,-0.124425,-0.087643,-0.090857,-0.029115,-0.071469,-0.065214,-0.085993,-0.067363,-0.148079,-0.044499,-0.037598,-0.158685,-0.108217,-0.073438,-0.139907,-0.11844,-0.176493,-0.133477,-0.077228,-0.029115,-0.12789,-0.058305,-0.159617,-0.069446,-0.16957,-0.047579,7.962412,-0.058305,-0.092424,-0.05321,-0.211749,-0.055815,-0.604532,-0.290701
4,-0.514782,0.747005,1.220244,-0.146380,1.001347,1.339993,0.436022,1.863770,-0.069446,-0.093965,-0.033624,-0.037598,-0.041193,-0.176493,-0.109545,-0.138855,-0.075356,-0.104138,-0.130152,-0.129025,-0.157747,-0.044499,-0.067363,-0.080845,12.649111,-0.080845,-0.110857,-0.095482,-0.047579,-0.071469,-0.041193,-0.041193,-0.016805,-0.029115,-0.132377,-0.041193,-0.075356,-0.060694,-0.075356,-0.099900,-0.105515,-0.023769,-0.102744,-0.082596,-0.041193,-0.050472,-0.037598,-0.05321,-0.138855,-0.055815,-0.055815,-0.016805,-0.120868,-0.134568,-0.05321,-0.055815,-0.113438,-0.037598,-0.055815,-0.126745,-0.047579,-0.055815,-0.067363,-0.12559,-0.112154,-0.041193,-0.131269,-0.044499,-0.062994,-0.062994,-0.085993,-0.05321,-0.12325,-0.077228,-0.044499,-0.047579,-0.055815,-0.065214,-0.108217,-0.067363,-0.062994,-0.065214,-0.156805,-0.108217,-0.115965,-0.077228,-0.092424,-0.164208,-0.0999,-0.11844,-0.124425,-0.087643,-0.090857,-0.029115,-0.071469,-0.065214,-0.085993,-0.067363,-0.148079,-0.044499,-0.037598,-0.158685,-0.108217,-0.073438,-0.139907,-0.11844,-0.176493,-0.133477,-0.077228,-0.029115,-0.12789,-0.058305,-0.159617,-0.069446,-0.16957,-0.047579,-0.125590,-0.058305,-0.092424,-0.05321,-0.211749,-0.055815,-0.604532,-0.290701

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_val_score

kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(LinearRegression(), X_scaled, y_log, cv=kfold, scoring='r2')

In [14]:
scores.mean(), scores.std()

(np.float64(0.8584695023553888), np.float64(0.018712122429398556))

In [15]:
lr = LinearRegression()

lr.fit(X_scaled, y_log)

LinearRegression()

In [16]:
lr.coef_

array([ 1.25894688e-01,  4.62583527e-02,  6.61747497e-02,  2.23853698e-02,
        2.15985093e-01,  4.67378954e-02,  5.77234774e-03,  4.31401962e-03,
        9.53057658e-03, -2.29663830e-02, -3.12403245e-03, -3.19244707e-03,
       -5.52258585e-03,  2.45127623e-02, -4.68598668e-03, -1.33467817e-03,
       -1.90780615e-02, -1.15918475e-03, -1.38589015e-02,  1.43462950e-02,
        2.19871410e-02,  4.78497389e-03, -1.49722033e-02,  9.29303146e-03,
        1.44987157e-02,  2.76848531e-02,  2.99538751e-02, -1.96243758e-02,
       -1.28109566e-02,  2.80177345e-02,  3.43419620e-03,  6.34442474e-03,
        4.20843929e-03,  1.25806652e-02,  6.11556353e-03, -9.04637662e-03,
        3.50075988e-02,  2.00276995e-03,  1.74068683e-02,  6.12894085e-02,
        7.32626200e-02,  7.06002312e-03,  4.23038914e-02, -1.24146074e-02,
       -1.06286981e-02, -1.39730167e-02,  6.63533360e-03,  2.29490529e-02,
        2.43568645e-02, -6.49633707e-03,  8.96845243e-03,  1.69316838e-03,
       -1.22179229e-02, -5.73781691e-04,  1.17718602e-02,  2.10583828e-03,
       -2.03887461e-02,  8.08497159e-03,  1.64632876e-02,  6.04920193e-02,
        2.67688308e-02,  1.61716374e-02,  1.26179324e-02,  5.20345959e-02,
        3.02610065e-02, -3.23420494e-03,  7.12066972e-02,  4.11348964e-04,
        4.60049246e-03,  4.62858361e-02,  4.51987678e-02,  1.25397218e-02,
        1.22017348e-02,  2.39522464e-02,  2.25211288e-02,  3.04804900e-02,
       -1.51074892e-02,  2.28009653e-02,  3.65140731e-02,  3.96559681e-02,
        3.21558896e-02,  2.40535752e-02,  6.76641786e-02,  5.10168392e-02,
        3.81902367e-02,  8.25539701e-03,  8.73791434e-03,  1.71284612e-02,
       -7.09531149e-03,  4.51396091e-03,  1.45232357e-02, -3.21016125e-03,
        2.65799127e-02, -2.46328791e-03,  1.90113631e-02,  8.02732931e-04,
       -6.25988175e-04, -5.49032993e-03,  1.09704337e-02, -1.33569988e-02,
       -2.14276351e-04,  1.35693626e-02, -1.25470211e-03,  8.26739612e-03,
       -1.82038268e-03, -1.23442935e-02,  4.62319084e-03, -5.86286984e-03,
        6.94584445e-03,  7.65291441e-05,  2.39103473e-03, -1.31389761e-02,
       -1.56006381e-02, -8.63940477e-04, -2.88044517e-02, -4.04883285e-03,
       -2.70031807e-02,  5.31589172e-04, -1.34406560e-02, -5.09339594e-03,
       -2.84568798e-02, -1.03080046e-02, -1.11804386e-02,  1.31178518e-02])

In [17]:
X_scaled.shape

(3542, 124)

In [19]:
coef_df = pd.DataFrame(lr.coef_.reshape(1, 124), columns=X_scaled.columns).stack().reset_index().drop(columns='level_0').rename(columns={'level_1': 'feature', 0: 'coefficient'})
coef_df.head(5)

         feature  coefficient
0  property_type     0.125895
1        bedRoom     0.046258
2       bathroom     0.066175
3       floorNum     0.022385
4   builtup_area     0.215985

#### Regression Analysis

In [20]:
import statsmodels.api as sm

X_with_const = sm.add_constant(X_scaled)

model = sm.OLS(y_log, X_with_const).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.870
Model:                            OLS   Adj. R-squared:                  0.865
Method:                 Least Squares   F-statistic:                     184.5
Date:                Wed, 11 Jun 2025   Prob (F-statistic):               0.00
Time:                        18:13:44   Log-Likelihood:                 683.01
No. Observations:                3542   AIC:                            -1116.
Df Residuals:                    3417   BIC:                            -344.5
Df Model:                         124
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
const                                 1.0425      0.003    305.413      0.000       1.036       1.049
property_type                         0.1259      0.005     23.688      0.000       0.115       0.136
bedRoom                               0.0463      0.006      7.137      0.000       0.034       0.059
bathroom                              0.0662      0.007      9.944      0.000       0.053       0.079
floorNum                              0.0224      0.004      5.700      0.000       0.015       0.030
builtup_area                          0.2160      0.005     42.760      0.000       0.206       0.226
servant room                          0.0467      0.004     10.516      0.000       0.038       0.055
furnishing_type                       0.0058      0.004      1.467      0.142      -0.002       0.013
facility_category                     0.0043      0.004      1.089      0.276      -0.003       0.012
sector_gwal pahari                    0.0095      0.006      1.572      0.116      -0.002       0.021
sector_manesar                       -0.0230      0.008     -3.025      0.003      -0.038      -0.008
sector_new                           -0.0031      0.004     -0.747      0.455      -0.011       0.005
sector_new sector 2                  -0.0032      0.004     -0.730      0.465      -0.012       0.005
sector_sector 1                      -0.0055      0.005     -1.216      0.224      -0.014       0.003
sector_sector 102                     0.0245      0.013      1.903      0.057      -0.001       0.050
sector_sector 103                    -0.0047      0.009     -0.548      0.583      -0.021       0.012
sector_sector 104                    -0.0013      0.010     -0.128      0.898      -0.022       0.019
sector_sector 105                    -0.0191      0.006     -2.946      0.003      -0.032      -0.006
sector_sector 106                    -0.0012      0.008     -0.141      0.888      -0.017       0.015
sector_sector 107                    -0.0139      0.010     -1.401      0.161      -0.033       0.006
sector_sector 108                     0.0143      0.010      1.461      0.144      -0.005       0.034
sector_sector 109                     0.0220      0.012      1.877      0.061      -0.001       0.045
sector_sector 10a                     0.0048      0.005      1.017      0.309      -0.004       0.014
sector_sector 11                     -0.0150      0.006     -2.501      0.012      -0.027      -0.003
sector_sector 110                     0.0093      0.007      1.374      0.169      -0.004       0.023
sector_sector 111                     0.0145      0.007      2.186      0.029       0.001       0.028
sector_sector 112                     0.0277      0.007      4.081      0.000       0.014       0.041
sector_sector 113                     0.0300      0.009      3.469      0.001       0.013       0.047
sector_sector 12                     -0.0196      0.008     -2.550      0.011      -0.035      -0.005
sector_sector 13                     -0.0128      0.005     -2.619      0.009      -0.022      -0.003
sector_sector 14                      0.0280      0.006      4.496      0.000       0.016       0.040
sector_sector 15                      0.0034      0.005      0.755      0.450      -0.005       0.012
sector_sector 17                      0.0063      0.005      1.392      0.164      -0.003       0.015
sector_sector 17a                     0.0042      0.004      1.158      0.247      -0.003       0.011
sector_sector 17b                     0.0126      0.004      3.114      0.002       0.005       0.021
sector_sector 2                       0.0061      0.010      0.606      0.544      -0.014       0.026
sector_sector 21                     -0.0090      0.005     -1.989      0.047      -0.018      -0.000
sector_sector 22                      0.0350      0.006      5.462      0.000       0.022       0.048
sector_sector 23                      0.0020      0.006      0.357      0.721      -0.009       0.013
sector_sector 24                      0.0174      0.006      2.698      0.007       0.005       0.030
sector_sector 25                      0.0613      0.008      7.626      0.000       0.046       0.077
sector_sector 26                      0.0733      0.008      8.715      0.000       0.057       0.090
sector_sector 27                      0.0071      0.004      1.836      0.066      -0.000       0.015
sector_sector 28                      0.0423      0.008      5.186      0.000       0.026       0.058
sector_sector 3                      -0.0124      0.007     -1.803      0.072      -0.026       0.001
sector_sector 3 phase 2              -0.0106      0.005     -2.344      0.019      -0.020      -0.002
sector_sector 3 phase 3 extension    -0.0140      0.005     -2.780      0.005      -0.024      -0.004
sector_sector 30                      0.0066      0.004      1.514      0.130      -0.002       0.015
sector_sector 31                      0.0229      0.005      4.432      0.000       0.013       0.033
sector_sector 33                      0.0244      0.010      2.346      0.019       0.004       0.045
sector_sector 36                     -0.0065      0.005     -1.231      0.219      -0.017       0.004
sector_sector 36a                     0.0090      0.005      1.693      0.091      -0.001       0.019
sector_sector 37                      0.0017      0.004      0.467      0.641      -0.005       0.009
sector_sector 37c                    -0.0122      0.009     -1.321      0.187      -0.030       0.006
sector_sector 37d                    -0.0006      0.010     -0.057      0.955      -0.020       0.019
sector_sector 38                      0.0118      0.005      2.275      0.023       0.002       0.022
sector_sector 39                      0.0021      0.005      0.397      0.691      -0.008       0.013
sector_sector 4                      -0.0204      0.009     -2.296      0.022      -0.038      -0.003
sector_sector 40                      0.0081      0.004      1.840      0.066      -0.001       0.017
sector_sector 41                      0.0165      0.005      3.088      0.002       0.006       0.027
sector_sector 43                      0.0605      0.010      6.228      0.000       0.041       0.080
sector_sector 45                      0.0268      0.005      5.490      0.000       0.017       0.036
sector_sector 46                      0.0162      0.005      3.020      0.003       0.006       0.027
sector_sector 47                      0.0126      0.006      2.115      0.034       0.001       0.024
sector_sector 48                      0.0520      0.010      5.384      0.000       0.033       0.071
sector_sector 49                      0.0303      0.009      3.458      0.001       0.013       0.047
sector_sector 5                      -0.0032      0.005     -0.710      0.478      -0.012       0.006
sector_sector 50                      0.0712      0.010      7.073      0.000       0.051       0.091
sector_sector 51                      0.0004      0.005      0.088      0.930      -0.009       0.010
sector_sector 52                      0.0046      0.006      0.807      0.420      -0.007       0.016
sector_sector 53                      0.0463      0.006      8.153      0.000       0.035       0.057
sector_sector 54                      0.0452      0.007      6.363      0.000       0.031       0.059
sector_sector 55                      0.0125      0.005      2.423      0.015       0.002       0.023
sector_sector 56                      0.0122      0.009      1.286      0.199      -0.006       0.031
sector_sector 57                      0.0240      0.007      3.633      0.000       0.011       0.037
sector_sector 58                      0.0225      0.005      4.788      0.000       0.013       0.032
sector_sector 59                      0.0305      0.005      6.304      0.000       0.021       0.040
sector_sector 6                      -0.0151      0.005     -2.839      0.005      -0.026      -0.005
sector_sector 60                      0.0228      0.006      3.905      0.000       0.011       0.034
sector_sector 61                      0.0365      0.008      4.339      0.000       0.020       0.053
sector_sector 62                      0.0397      0.006      6.655      0.000       0.028       0.051
sector_sector 63                      0.0322      0.006      5.647      0.000       0.021       0.043
sector_sector 63a                     0.0241      0.006      4.157      0.000       0.013       0.035
sector_sector 65                      0.0677      0.012      5.827      0.000       0.045       0.090
sector_sector 66                      0.0510      0.009      6.000      0.000       0.034       0.068
sector_sector 67                      0.0382      0.009      4.235      0.000       0.021       0.056
sector_sector 67a                     0.0083      0.007      1.266      0.206      -0.005       0.021
sector_sector 68                      0.0087      0.007      1.170      0.242      -0.006       0.023
sector_sector 69                      0.0171      0.012      1.415      0.157      -0.007       0.041
sector_sector 7                      -0.0071      0.008     -0.885      0.376      -0.023       0.009
sector_sector 70                      0.0045      0.009      0.495      0.620      -0.013       0.022
sector_sector 70a                     0.0145      0.010      1.523      0.128      -0.004       0.033
sector_sector 71                     -0.0032      0.007     -0.447      0.655      -0.017       0.011
sector_sector 72                      0.0266      0.007      3.585      0.000       0.012       0.041
sector_sector 73                     -0.0025      0.004     -0.614      0.539      -0.010       0.005
sector_sector 74                      0.0190      0.006      3.054      0.002       0.007       0.031
sector_sector 76                      0.0008      0.006      0.139      0.890      -0.011       0.012
sector_sector 77                     -0.0006      0.007     -0.088      0.930      -0.015       0.013
sector_sector 78                     -0.0055      0.006     -0.923      0.356      -0.017       0.006
sector_sector 79                      0.0110      0.011      0.993      0.321      -0.011       0.033
sector_sector 8                      -0.0134      0.005     -2.825      0.005      -0.023      -0.004
sector_sector 80                     -0.0002      0.004     -0.049      0.961      -0.009       0.008
sector_sector 81                      0.0136      0.012      1.155      0.248      -0.009       0.037
sector_sector 82                     -0.0013      0.008     -0.148      0.882      -0.018       0.015
sector_sector 82a                     0.0083      0.006      1.311      0.190      -0.004       0.021
sector_sector 83                     -0.0018      0.011     -0.173      0.863      -0.023       0.019
sector_sector 84                     -0.0123      0.009     -1.350      0.177      -0.030       0.006
sector_sector 85                      0.0046      0.013      0.359      0.719      -0.021       0.030
sector_sector 86                     -0.0059      0.010     -0.580      0.562      -0.026       0.014
sector_sector 88a                     0.0069      0.007      1.064      0.288      -0.006       0.020
sector_sector 88b                  7.653e-05      0.004      0.019      0.985      -0.008       0.008
sector_sector 89                      0.0024      0.010      0.247      0.805      -0.017       0.021
sector_sector 9                      -0.0131      0.005     -2.402      0.016      -0.024      -0.002
sector_sector 90                     -0.0156      0.012     -1.321      0.187      -0.039       0.008
sector_sector 91                     -0.0009      0.006     -0.142      0.887      -0.013       0.011
sector_sector 92                     -0.0288      0.012     -2.323      0.020      -0.053      -0.004
sector_sector 93                     -0.0040      0.005     -0.835      0.404      -0.014       0.005
sector_sector 95                     -0.0270      0.010     -2.812      0.005      -0.046      -0.008
sector_sector 99                      0.0005      0.005      0.098      0.922      -0.010       0.011
sector_sector 99a                    -0.0134      0.007     -1.803      0.071      -0.028       0.001
sector_sector 9a                     -0.0051      0.005     -0.986      0.324      -0.015       0.005
sector_sohna road                    -0.0285      0.015     -1.888      0.059      -0.058       0.001
sector_sohna road road               -0.0103      0.005     -1.948      0.051      -0.021    6.66e-05
agePossession_old                    -0.0112      0.005     -2.287      0.022      -0.021      -0.002
agePossession_under_construction      0.0131      0.004      3.298      0.001       0.005       0.021
==============================================================================
Omnibus:                      552.829   Durbin-Watson:                   1.940
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5695.193
Skew:                          -0.408   Prob(JB):                         0.00
Kurtosis:                       9.158   Cond. No.                         40.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## Standardized Regression Coefficients
**Formula:**  
```Stand. Coef (X) = UnStand. Coef (X) * (SD(X) / SD(Y))```  
we have the value of st. coef(x) and we want to find unstd. coef(x) value.  

therefore, formula becomes  
```UnStd. Coef(x) = Std. Coef.(X) * (SD(Y) / SD(X))```

In [ ]:
# get the st. deviation values of X and y

X_std = X_scaled['bedRoom'].std()
y_std = y_log.std()


unstd_coef_bedroom = 0.046258 * (y_std / X_std) # unstandardized coefficient for bedRoom

# need to consider exponent of the coefficient, because we applied log transformation on y
unstd_coef_bedroom_exp = np.expm1(unstd_coef_bedroom) 
unstd_coef_bedroom_exp

np.float64(0.025935795864130338)

In [24]:
# doing the same for builtup_area
X_std_builtup = X_scaled['builtup_area'].std()

unstd_coef_builtup = 0.215985 * (y_std / X_std_builtup) # unstandardized coefficient for builtup_area

unstd_coef_builtup_exp = np.expm1(unstd_coef_builtup)
unstd_coef_builtup_exp

np.float64(0.12699417819109354)